version: "3.3"
services: 
  ngnixapp:
     image: swamipeddineni/ngnix:${buildNumber}
     ports:
    - 8081:80
  networks:
  - ngnixnetwork
networks:
   ngnixnetwork:
     driver: bridge 
  


     

